spring:
  application:
    name: demo
  kafka:
    bootstrap-servers: localhost:9092
    #    template:
    #      default-topic: person
    producer:
      #      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      in:
        topic: in
        key-serializer: org.apache.kafka.common.serialization.VoidSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      out:
        topic: out
        key-serializer: org.apache.kafka.common.serialization.VoidSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        tx-prefix: tx-person-out
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: person-group-id
      properties:
        spring:
          json:
            trusted.packages: "*"
            use.type.headers: false
            value.default.type: com.playground.demo.model.Person
        isolation.level: read_committed

logging:
  level.root: ERROR
  level:
    com.playground.demo: debug
    org.apache.kafka: ERROR
    org.springframework.kafka.transaction: trace
    org.springframework.kafka.core.DefaultKafkaProducerFactory: trace