spring:
  application:
    name: demo
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: person
    producer:
      key-serializer: org.apache.kafka.common.serialization.VoidSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: person-group-id
      properties:
        spring:
          json:
            trusted.packages: "*"
            use.type.headers: false
            value.default.type: com.playground.demo.model.Person

logging:
  level.root: info
  level:
    org.apache.kafka: ERROR